<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PassyouController;
use App\Http\Controllers\SaplikasiController;
use App\Http\Controllers\HisuserController;
use App\Http\Controllers\BackupController;
use App\Http\Controllers\ResetController;
use App\Http\Controllers\UpdateprofileController;
use App\Http\Controllers\TbbarangController;
use App\Http\Controllers\TbbankController;
use App\Http\Controllers\TbasuransiController;
use App\Http\Controllers\TbcabangController;
use App\Http\Controllers\TbdivisiController;
use App\Http\Controllers\TbagamaController;
use App\Http\Controllers\TbsaController;
use App\Http\Controllers\TbmekanikController;
use App\Http\Controllers\TbklpjasaController;
use App\Http\Controllers\TboplController;
use App\Http\Controllers\Tasklist_bpController;
use App\Http\Controllers\Tasklisttipe_bpController;
use App\Http\Controllers\Tasklisttipe_bpdController;

use App\Http\Controllers\TbmerekController;
use App\Http\Controllers\TbmodelController;
use App\Http\Controllers\TbwarnaController;
use App\Http\Controllers\TbtipeController;
use App\Http\Controllers\TbjenixController;
use App\Http\Controllers\TbmobilController;
use App\Http\Controllers\TbgudangController;
use App\Http\Controllers\TbjntransController;
use App\Http\Controllers\TbjnbrgController;
use App\Http\Controllers\TbsatuanController;
use App\Http\Controllers\TbnegaraController;
use App\Http\Controllers\TbmoveController;
use App\Http\Controllers\TbdiscountController;
use App\Http\Controllers\TbklpcustController;
use App\Http\Controllers\TbcustomerController;
use App\Http\Controllers\TbsupplierController;
use App\Http\Controllers\TbmultiprcController;
use App\Http\Controllers\TbsalesController;
use App\Http\Controllers\TbleasingController;
use App\Http\Controllers\TbjnstrmksrController;
use App\Http\Controllers\TbpaketController;
use App\Http\Controllers\Tbpaket_detailController;
use App\Http\Controllers\TbbahanController;
use App\Http\Controllers\TbjasaController;

use App\Http\Controllers\TbjnkeluarController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TbmoduleController;
use App\Http\Controllers\CariController;
use App\Http\Controllers\SoController;
use App\Http\Controllers\SodController;
use App\Http\Controllers\Estimasi_bpController;
use App\Http\Controllers\Estimasi_bpdController;
use App\Http\Controllers\Wo_bpController;
use App\Http\Controllers\Wo_bpdController;
use App\Http\Controllers\Faktur_bpController;
use App\Http\Controllers\Faktur_bpdController;
use App\Http\Controllers\Jasa_bpController;
use App\Http\Controllers\Part_bpController;
use App\Http\Controllers\Bahan_bpController;
use App\Http\Controllers\Opl_bpController;

use App\Http\Controllers\Estimasi_grController;
use App\Http\Controllers\Estimasi_grdController;
use App\Http\Controllers\Wo_grController;
use App\Http\Controllers\Wo_grdController;
use App\Http\Controllers\Faktur_grController;
use App\Http\Controllers\Faktur_grdController;
use App\Http\Controllers\Jasa_grController;
use App\Http\Controllers\Part_grController;
use App\Http\Controllers\Bahan_grController;
use App\Http\Controllers\Opl_grController;

use App\Http\Controllers\JualController;
use App\Http\Controllers\JualdController;
use App\Http\Controllers\PoController;
use App\Http\Controllers\PodController;
use App\Http\Controllers\BeliController;
use App\Http\Controllers\BelidController;
use App\Http\Controllers\TerimaController;
use App\Http\Controllers\TerimadController;
use App\Http\Controllers\KeluarController;
use App\Http\Controllers\KeluardController;
use App\Http\Controllers\OpnameController;
use App\Http\Controllers\OpnamedController;
use App\Http\Controllers\Approv_batas_piutangController;
use App\Http\Controllers\Kasir_tunaiController;
use App\Http\Controllers\Kasir_tagihanController;
use App\Http\Controllers\Kasir_tagihandController;
use App\Http\Controllers\MohklruangController;
use App\Http\Controllers\MohklruangdController;
use App\Http\Controllers\Kasir_keluarController;
use App\Http\Controllers\Kasir_keluardController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ProsesController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\symlink;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::resource('/', \App\Http\Controllers\LoginController::class);
// Route::resource('home', \App\Http\Controllers\HomeController::class);

// Route::get('flights', function () {
//   // Only authenticated users may access this route...
// })->middleware('auth');

//Login
// Route::get('download', function () {
//   return response()->download(storage_path('app/public/backup/pos-06-11-2023 10-09-14.sql'));
// });

Route::middleware('auth')->group(function () {
  //Home
  Route::get('home', [HomeController::class, 'index'])->name('index');
  Route::get('contact', [HomeController::class, 'contact'])->name('contact');
  Route::get('actionlogout', [LoginController::class, 'actionlogout'])->name('actionlogout');
  //Dashboard
  Route::get('dashboard', [DashboardController::class, 'index'])->name('index');
  Route::get('grafik', [DashboardController::class, 'grafik'])->name('grafik');
  Route::resource('/user', \App\Http\Controllers\UserController::class);
  Route::resource('/passyou', \App\Http\Controllers\PassyouController::class);
  Route::resource('/updateprofile', \App\Http\Controllers\UpdateprofileController::class);
  //Tbmodule
  Route::resource('/tbmodule', \App\Http\Controllers\TbmoduleController::class);
  Route::get('tbmoduleajax', [TbmoduleController::class, 'tbmoduleajax'])->name('tbmoduleajax');
  Route::get('tbmodule_urutkan', [TbmoduleController::class, 'tbmodule_urutkan'])->name('tbmodule_urutkan');
  //Users
  // Route::get('users', [UsersController::class, 'index'])->name('users.index');
  Route::get('userajax', [UserController::class, 'userajax'])->name('userajax');
  // Route::get('user_show', [UserController::class, 'show'])->name('user_show');
  Route::get('user_akses', [UserController::class, 'user_akses'])->name('user_akses');
  Route::post('simpanakses', [UserController::class, 'simpanakses'])->name('simpanakses');
  //Saplikasi
  Route::resource('/saplikasi', \App\Http\Controllers\SaplikasiController::class);
  Route::get('saplikasiajax', [SaplikasiController::class, 'saplikasiajax'])->name('saplikasiajax');
  //Hisuser
  Route::resource('/hisuser', \App\Http\Controllers\HisuserController::class);
  Route::get('hisuserajax', [HisuserController::class, 'hisuserajax'])->name('hisuserajax');
  //Backup
  Route::resource('/backup', \App\Http\Controllers\BackupController::class);
  Route::get('backup_proses', [BackupController::class, 'backup_proses'])->name('backup_proses');
  Route::get('reset', [ResetController::class, 'reset'])->name('reset');
  Route::get('reset_proses', [ResetController::class, 'reset_proses'])->name('reset_proses');
  Route::get('alter_proses', [ResetController::class, 'alter_proses'])->name('alter_proses');
  // Tabel-tabel
  Route::resource('/tbmerek', \App\Http\Controllers\TbmerekController::class);
  Route::get('tbmerekajax', [TbmerekController::class, 'tbmerekajax'])->name('tbmerekajax');
  Route::resource('/tbmodel', \App\Http\Controllers\TbmodelController::class);
  Route::get('tbmodelajax', [TbmodelController::class, 'tbmodelajax'])->name('tbmodelajax');
  Route::resource('/tbwarna', \App\Http\Controllers\TbwarnaController::class);
  Route::get('tbwarnaajax', [TbwarnaController::class, 'tbwarnaajax'])->name('tbwarnaajax');
  Route::resource('/tbtipe', \App\Http\Controllers\TbtipeController::class);
  Route::get('tbtipeajax', [TbtipeController::class, 'tbtipeajax'])->name('tbtipeajax');
  // Route::resource('/tbjenis', \App\Http\Controllers\TbjenisController::class);
  Route::resource('/tbjenix', \App\Http\Controllers\TbjenixController::class);
  Route::get('tbjenixajax', [TbjenixController::class, 'tbjenixajax'])->name('tbjenixajax');
  Route::resource('/tbmobil', \App\Http\Controllers\TbmobilController::class);
  Route::get('tbmobilajax', [TbmobilController::class, 'tbmobilajax'])->name('tbmobilajax');
  Route::get('tambahcustomer', [TbmobilController::class, 'tambahcustomer'])->name('tambahcustomer');
  Route::resource('/tbbank', \App\Http\Controllers\TbbankController::class);
  Route::get('tbbankajax', [TbbankController::class, 'tbbankajax'])->name('tbbankajax');
  Route::resource('/tbasuransi', \App\Http\Controllers\TbasuransiController::class);
  Route::get('tbasuransiajax', [TbasuransiController::class, 'tbasuransiajax'])->name('tbasuransiajax');
  Route::resource('/tbcabang', \App\Http\Controllers\TbcabangController::class);
  Route::get('tbcabangajax', [TbcabangController::class, 'tbcabangajax'])->name('tbcabangajax');
  Route::resource('/tbdivisi', \App\Http\Controllers\TbdivisiController::class);
  Route::get('tbdivisiajax', [TbdivisiController::class, 'tbdivisiajax'])->name('tbdivisiajax');
  Route::resource('/tbagama', \App\Http\Controllers\TbagamaController::class);
  Route::get('tbagamaajax', [TbagamaController::class, 'tbagamaajax'])->name('tbagamaajax');
  Route::resource('/tbsa', \App\Http\Controllers\TbsaController::class);
  Route::get('tbsaajax', [TbsaController::class, 'tbsaajax'])->name('tbsaajax');
  Route::resource('/tbmekanik', \App\Http\Controllers\TbmekanikController::class);
  Route::get('tbmekanikajax', [TbmekanikController::class, 'tbmekanikajax'])->name('tbmekanikajax');
  Route::resource('/tbklpjasa', \App\Http\Controllers\TbklpjasaController::class);
  Route::get('tbklpjasaajax', [TbklpjasaController::class, 'tbklpjasaajax'])->name('tbklpjasaajax');

  Route::resource('/tbpaket', \App\Http\Controllers\TbpaketController::class);
  Route::get('tbpaketajax', [TbpaketController::class, 'tbpaketajax'])->name('tbpaketajax');
  Route::resource('/tbpaket_detail', \App\Http\Controllers\Tbpaket_detailController::class);
  Route::get('tbpaket_detail', [Tbpaket_detailController::class, 'index'])->name('index');
  Route::get('paketjasaajax', [Tbpaket_detailController::class, 'paketjasaajax'])->name('paketjasaajax');
  Route::post('simpanpaketjasa', [Tbpaket_detailController::class, 'simpanpaketjasa'])->name('simpanpaketjasa');
  Route::get('paketpartajax', [Tbpaket_detailController::class, 'paketpartajax'])->name('paketpartajax');
  Route::post('simpanpaketpart', [Tbpaket_detailController::class, 'simpanpaketpart'])->name('simpanpaketpart');
  Route::get('editpaketjasa', [Tbpaket_detailController::class, 'editpaketjasa'])->name('editpaketjasa');
  Route::get('updatepaketjasa', [Tbpaket_detailController::class, 'updatepaketjasa'])->name('updatepaketjasa');
  Route::get('editpaketpart', [Tbpaket_detailController::class, 'editpaketpart'])->name('editpaketpart');
  Route::get('updatepaketpart', [Tbpaket_detailController::class, 'updatepaketpart'])->name('updatepaketpart');
  Route::get('paketbahanajax', [Tbpaket_detailController::class, 'paketbahanajax'])->name('paketbahanajax');
  Route::post('simpanpaketbahan', [Tbpaket_detailController::class, 'simpanpaketbahan'])->name('simpanpaketbahan');
  Route::get('editpaketbahan', [Tbpaket_detailController::class, 'editpaketbahan'])->name('editpaketbahan');
  Route::get('updatepaketbahan', [Tbpaket_detailController::class, 'updatepaketbahan'])->name('updatepaketbahan');
  Route::get('paketoplajax', [Tbpaket_detailController::class, 'paketoplajax'])->name('paketoplajax');
  Route::post('simpanpaketopl', [Tbpaket_detailController::class, 'simpanpaketopl'])->name('simpanpaketopl');
  Route::get('editpaketopl', [Tbpaket_detailController::class, 'editpaketopl'])->name('editpaketopl');
  Route::get('updatepaketopl', [Tbpaket_detailController::class, 'updatepaketopl'])->name('updatepaketopl');

  Route::resource('/tbjasa', \App\Http\Controllers\TbjasaController::class);
  Route::get('tbjasaajax', [TbjasaController::class, 'tbjasaajax'])->name('tbjasaajax');
  Route::resource('/tbbahan', \App\Http\Controllers\TbbahanController::class);
  Route::get('tbbahanajax', [TbbahanController::class, 'tbbahanajax'])->name('tbbahanajax');
  Route::resource('/tbopl', \App\Http\Controllers\TboplController::class);
  Route::get('tboplajax', [TboplController::class, 'tboplajax'])->name('tboplajax');
  Route::resource('/tasklist_bp', \App\Http\Controllers\Tasklist_bpController::class);
  Route::get('tasklist_bpajax', [Tasklist_bpController::class, 'tasklist_bpajax'])->name('tasklist_bpajax');

  Route::resource('/tasklisttipe_bp', \App\Http\Controllers\Tasklisttipe_bpController::class);
  Route::get('tasklisttipe_bpajax', [Tasklisttipe_bpController::class, 'tasklisttipe_bpajax'])->name('tasklisttipe_bpajax');
  Route::resource('/tasklisttipe_bpd', \App\Http\Controllers\Tasklisttipe_bpdController::class);
  Route::get('tasklisttipe_bpd', [Tasklisttipe_bpdController::class, 'index'])->name('index');
  Route::get('tasklisttipe_bpdajax', [Tasklisttipe_bpdController::class, 'tasklisttipe_bpdajax'])->name('tasklisttipe_bpdajax');
  Route::post('simpantasklisttipe_bpd', [Tasklisttipe_bpdController::class, 'simpantasklisttipe_bpd'])->name('simpantasklisttipe_bpd');
  Route::get('edittasklisttipe_bpd', [Tasklisttipe_bpdController::class, 'edittasklisttipe_bpd'])->name('edittasklisttipe_bpd');
  Route::get('updatetasklisttipe_bpd', [Tasklisttipe_bpdController::class, 'updatetasklisttipe_bpd'])->name('updatetasklisttipe_bpd');
  Route::post('salintasklisttipe_bpd', [Tasklisttipe_bpdController::class, 'salintasklisttipe_bpd'])->name('salintasklisttipe_bpd');

  Route::resource('/tbjnkeluar', \App\Http\Controllers\TbjnkeluarController::class);
  Route::get('tbjnkeluarajax', [TbjnkeluarController::class, 'tbjnkeluarajax'])->name('tbjnkeluarajax');
  Route::resource('/tbgudang', \App\Http\Controllers\TbgudangController::class);
  Route::get('tbgudangajax', [TbgudangController::class, 'tbgudangajax'])->name('tbgudangajax');
  Route::resource('/tbjntrans', \App\Http\Controllers\TbjntransController::class);
  Route::get('tbjntransajax', [TbjntransController::class, 'tbjntransajax'])->name('tbjntransajax');
  Route::resource('/tbjnbrg', \App\Http\Controllers\TbjnbrgController::class);
  Route::get('tbjnbrgajax', [TbjnbrgController::class, 'tbjnbrgajax'])->name('tbjnbrgajax');
  Route::resource('/tbsatuan', \App\Http\Controllers\TbsatuanController::class);
  Route::get('tbsatuanajax', [TbsatuanController::class, 'tbsatuanajax'])->name('tbsatuanajax');
  Route::resource('/tbnegara', \App\Http\Controllers\TbnegaraController::class);
  Route::get('tbnegaraajax', [TbnegaraController::class, 'tbnegaraajax'])->name('tbnegaraajax');
  Route::resource('/tbmove', \App\Http\Controllers\TbmoveController::class);
  Route::get('tbmoveajax', [TbmoveController::class, 'tbmoveajax'])->name('tbmoveajax');
  Route::resource('/tbdiscount', \App\Http\Controllers\TbdiscountController::class);
  Route::get('tbdiscountajax', [TbdiscountController::class, 'tbdiscountajax'])->name('tbdiscountajax');
  Route::resource('/tbklpcust', \App\Http\Controllers\TbklpcustController::class);
  Route::get('tbklpcustajax', [TbklpcustController::class, 'tbklpcustajax'])->name('tbklpcustajax');
  Route::resource('/tbcustomer', \App\Http\Controllers\TbcustomerController::class);
  Route::get('tbcustomerajax', [TbcustomerController::class, 'tbcustomerajax'])->name('tbcustomerajax');
  Route::get('cariklpcust', [TbcustomerController::class, 'cariklpcust'])->name('cariklpcust');
  Route::get('replklpcust', [TbcustomerController::class, 'replklpcust'])->name('replklpcust');
  Route::resource('/tbsupplier', \App\Http\Controllers\TbsupplierController::class);
  Route::get('tbsupplierajax', [TbsupplierController::class, 'tbsupplierajax'])->name('tbsupplierajax');
  Route::resource('/tbsales', \App\Http\Controllers\TbsalesController::class);
  Route::get('tbsalesajax', [TbsalesController::class, 'tbsalesajax'])->name('tbsalesajax');
  Route::resource('/tbleasing', \App\Http\Controllers\TbleasingController::class);
  Route::get('tbleasingajax', [TbleasingController::class, 'tbleasingajax'])->name('tbleasingajax');
  Route::resource('/tbjnstrmksr', \App\Http\Controllers\TbjnstrmksrController::class);
  Route::get('tbjnstrmksrajax', [TbjnstrmksrController::class, 'tbjnstrmksrajax'])->name('tbjnstrmksrajax');

  Route::resource('/tbmultiprc', \App\Http\Controllers\TbmultiprcController::class);
  Route::get('tbmultiprcajax', [TbmultiprcController::class, 'tbmultiprcajax'])->name('tbmultiprcajax');
  Route::get('inputmultiprc', [TbmultiprcController::class, 'inputmultiprc'])->name('inputmultiprc');
  // Route::get('caritbcustomer', [TbmultiprcController::class, 'caritbcustomer'])->name('caritbcustomer');
  // Route::get('repltbcustomer', [TbmultiprcController::class, 'repltbcustomer'])->name('repltbcustomer');
  // Route::get('caritbbarang', [TbmultiprcController::class, 'caritbbarang'])->name('caritbbarang');
  // Route::get('repltbbarang', [TbmultiprcController::class, 'repltbbarang'])->name('repltbbarang');
  Route::get('multiprc_table', [TbmultiprcController::class, 'multiprc_table'])->name('multiprc_table');
  Route::get('multiprc_simpan', [TbmultiprcController::class, 'multiprc_simpan'])->name('multiprc_simpan');
  Route::get('multiprc_salin_tbbarang', [TbmultiprcController::class, 'multiprc_salin_tbbarang'])->name('multiprc_salin_tbbarang');
  Route::get('multiprc_salin_tbbarang_customer', [TbmultiprcController::class, 'multiprc_salin_tbbarang_customer'])->name('multiprc_salin_tbbarang_customer');
  Route::get('multiprc_edit', [TbmultiprcController::class, 'multiprc_edit'])->name('multiprc_edit');
  Route::post('multiprc_update', [TbmultiprcController::class, 'multiprc_update'])->name('multiprc_update');
  Route::resource('/tbbarang', \App\Http\Controllers\TbbarangController::class);
  Route::get('tbbarangajax', [TbbarangController::class, 'tbbarangajax'])->name('tbbarangajax');
  Route::get('ambildatatbmerek', [TbmodelController::class, 'ambildatatbmerek'])->name('ambildatatbmerek');
  Route::get('ambildatatbmodel', [TbtipeController::class, 'ambildatatbmodel'])->name('ambildatatbmodel');
  Route::get('ambildatatbtipe', [TbtipeController::class, 'ambildatatbtipe'])->name('ambildatatbtipe');
  Route::get('ambildatatbnegara', [TbbarangController::class, 'ambildatatbnegara'])->name('ambildatatbnegara');
  Route::get('ambildatatbjnbrg', [TbbarangController::class, 'ambildatatbjnbrg'])->name('ambildatatbjnbrg');
  Route::get('ambildatatbmove', [TbbarangController::class, 'ambildatatbmove'])->name('ambildatatbmove');
  Route::get('ambildatatbdiscount', [TbbarangController::class, 'ambildatatbdiscount'])->name('ambildatatbdiscount');
  Route::get('ambildatatbsatuan', [TbbarangController::class, 'ambildatatbsatuan'])->name('ambildatatbsatuan');
  Route::get('carinegara', [TbbarangController::class, 'carinegara'])->name('carinegara');
  Route::get('replnegara', [TbbarangController::class, 'replnegara'])->name('replnegara');

  // Transaksi
  Route::get('caripemakai', [CariController::class, 'caripemakai'])->name('caripemakai');
  Route::get('replpemakai', [CariController::class, 'replpemakai'])->name('replpemakai');
  Route::get('caripemilik', [CariController::class, 'caripemilik'])->name('caripemilik');
  Route::get('replpemilik', [CariController::class, 'replpemilik'])->name('replpemilik');
  Route::get('cariasuransi', [CariController::class, 'cariasuransi'])->name('cariasuransi');
  Route::get('replasuransi', [CariController::class, 'replasuransi'])->name('replasuransi');
  Route::get('cariasuransi_es', [CariController::class, 'cariasuransi_es'])->name('cariasuransi_es');
  Route::get('replasuransi_es', [CariController::class, 'replasuransi'])->name('replasuransi');
  Route::get('cariklpcust', [CariController::class, 'cariklpcust'])->name('cariklpcust');
  Route::get('replklpcust', [CariController::class, 'replklpcust'])->name('replklpcust');
  Route::get('caricustomer', [CariController::class, 'caricustomer'])->name('caricustomer');
  Route::get('replcustomer', [CariController::class, 'replcustomer'])->name('replcustomer');
  Route::get('carisales', [CariController::class, 'carisales'])->name('carisales');
  Route::get('replsales', [CariController::class, 'replsales'])->name('replsales');
  Route::get('caritbbank', [CariController::class, 'caritbbank'])->name('caritbbank');
  Route::get('repltbbank', [CariController::class, 'repltbbank'])->name('repltbbank');
  Route::get('caritbjnskartu', [CariController::class, 'caritbjnskartu'])->name('caritbjnskartu');
  Route::get('repltbjnskartu', [CariController::class, 'repltbjnskartu'])->name('repltbjnskartu');
  Route::get('caritbbarang', [CariController::class, 'caritbbarang'])->name('caritbbarang');
  Route::get('repltbbarang', [CariController::class, 'repltbbarang'])->name('repltbbarang');
  Route::get('caritbmultiprc', [CariController::class, 'caritbmultiprc'])->name('caritbmultiprc');
  Route::get('repltbmultiprc', [CariController::class, 'repltbmultiprc'])->name('repltbmultiprc');
  Route::get('carisupplier', [CariController::class, 'carisupplier'])->name('carisupplier');
  Route::get('carisupplierdetail', [CariController::class, 'carisupplierdetail'])->name('carisupplierdetail');
  Route::get('replsupplier', [CariController::class, 'replsupplier'])->name('replsupplier');
  Route::get('carijual', [CariController::class, 'carijual'])->name('carijual');
  Route::get('carijualpiutang', [CariController::class, 'carijualpiutang'])->name('carijualpiutang');
  Route::get('repljual', [CariController::class, 'repljual'])->name('repljual');
  Route::get('repljualpiutang', [CariController::class, 'repljualpiutang'])->name('repljualpiutang');
  Route::get('carimohklruang', [CariController::class, 'carimohklruang'])->name('carimohklruang');
  Route::get('replmohklruang', [CariController::class, 'replmohklruang'])->name('replmohklruang');
  Route::get('caribeli', [CariController::class, 'caribeli'])->name('caribeli');
  Route::get('replbeli', [CariController::class, 'replbeli'])->name('replbeli');
  Route::get('tampilpembayaran', [CariController::class, 'tampilpembayaran'])->name('tampilpembayaran');
  Route::get('carijasa', [CariController::class, 'carijasa'])->name('carijasa');
  Route::get('repljasa', [CariController::class, 'repljasa'])->name('repljasa');
  Route::get('caripart', [CariController::class, 'caripart'])->name('caripart');
  Route::get('replpart', [CariController::class, 'replpart'])->name('replpart');
  Route::get('caribahan', [CariController::class, 'caribahan'])->name('caribahan');
  Route::get('replbahan', [CariController::class, 'replbahan'])->name('replbahan');
  Route::get('cariopl', [CariController::class, 'cariopl'])->name('cariopl');
  Route::get('replopl', [CariController::class, 'replopl'])->name('replopl');
  Route::get('caritlbp', [CariController::class, 'caritlbp'])->name('caritlbp');
  Route::get('repltlbp', [CariController::class, 'repltlbp'])->name('repltlbp');
  Route::get('caritltipebp', [CariController::class, 'caritltipebp'])->name('caritltipebp');
  Route::get('repltltipebp', [CariController::class, 'repltltipebp'])->name('repltltipebp');
  Route::get('carisa', [CariController::class, 'carisa'])->name('carisa');
  Route::get('replsa', [CariController::class, 'replsa'])->name('replsa');
  Route::get('carijasa_bp', [CariController::class, 'carijasa_bp'])->name('carijasa_bp');
  Route::get('repljasa_bp', [CariController::class, 'repljasa_bp'])->name('repljasa_bp');
  Route::get('caripart_bp', [CariController::class, 'caripart_bp'])->name('caripart_bp');
  Route::get('replpart_bp', [CariController::class, 'replpart_bp'])->name('replpart_bp');
  Route::get('caribahan_bp', [CariController::class, 'caribahan_bp'])->name('caribahan_bp');
  Route::get('replbahan_bp', [CariController::class, 'replbahan_bp'])->name('replbahan_bp');
  Route::get('cariopl_bp', [CariController::class, 'cariopl_bp'])->name('cariopl_bp');
  Route::get('replopl_bp', [CariController::class, 'replopl_bp'])->name('replopl_bp');
  Route::get('cariwo_bp', [CariController::class, 'cariwo_bp'])->name('cariwo_bp');
  Route::get('replwo_bp', [CariController::class, 'replwo_bp'])->name('replwo_bp');
  Route::get('carijasa_gr', [CariController::class, 'carijasa_gr'])->name('carijasa_gr');
  Route::get('repljasa_gr', [CariController::class, 'repljasa_gr'])->name('repljasa_gr');
  Route::get('caripart_gr', [CariController::class, 'caripart_gr'])->name('caripart_gr');
  Route::get('replpart_gr', [CariController::class, 'replpart_gr'])->name('replpart_gr');
  Route::get('caribahan_gr', [CariController::class, 'caribahan_gr'])->name('caribahan_gr');
  Route::get('replbahan_gr', [CariController::class, 'replbahan_gr'])->name('replbahan_gr');
  Route::get('cariopl_gr', [CariController::class, 'cariopl_gr'])->name('cariopl_gr');
  Route::get('replopl_gr', [CariController::class, 'replopl_gr'])->name('replopl_gr');
  Route::get('cariwo_gr', [CariController::class, 'cariwo_gr'])->name('cariwo_gr');
  Route::get('replwo_gr', [CariController::class, 'replwo_gr'])->name('replwo_gr');

  //Estimasi WO Body Repair
  Route::resource('/estimasi_bp', \App\Http\Controllers\Estimasi_bpController::class);
  Route::get('estimasi_bp', [Estimasi_bpController::class, 'index'])->name('index');
  Route::get('tbmobil_bpajax', [Estimasi_bpController::class, 'tbmobil_bpajax'])->name('tbmobil_bpajax');
  Route::post('tbmobil_update', [Estimasi_bpController::class, 'tbmobil_update'])->name('tbmobil_update');
  Route::post('estimasi_bp_create', [Estimasi_bpController::class, 'estimasi_bp_create'])->name('estimasi_bp_create');
  Route::post('estimasi_bp_tambah', [Estimasi_bpController::class, 'estimasi_bp_tambah'])->name('estimasi_bp_tambah');
  Route::post('estimasi_bp_edit', [Estimasi_bpController::class, 'estimasi_bp_create'])->name('estimasi_bp_create');
  // Route::post('estimasi_bp_update', [Estimasi_bpController::class, 'estimasi_bp_update'])->name('estimasi_bp_simpan');
  Route::resource('/tbmobil_bp', \App\Http\Controllers\Estimasi_bpController::class);
  Route::get('estimasi_bpajax', [Estimasi_bpController::class, 'estimasi_bpajax'])->name('estimasi_bpajax');
  Route::get('estimasi_bpupdate', [Estimasi_bpController::class, 'update'])->name('update');
  Route::get('detailestimasi_bp', [Estimasi_bpController::class, 'detailestimasi_bp'])->name('detailestimasi_bp');
  Route::post('estimasi_bpproses', [Estimasi_bpController::class, 'estimasi_bpproses'])->name('estimasi_bpproses');
  Route::get('estimasi_bpunproses', [Estimasi_bpController::class, 'estimasi_bpunproses'])->name('estimasi_bpunproses');
  Route::post('estimasi_bpunproses_simpan', [Estimasi_bpController::class, 'estimasi_bpunproses_simpan'])->name('estimasi_bpunproses_simpan');
  Route::post('estimasi_bpcancel', [Estimasi_bpController::class, 'estimasi_bpcancel'])->name('estimasi_bpcancel');
  Route::post('estimasi_bpambil', [Estimasi_bpController::class, 'estimasi_bpambil'])->name('estimasi_bpambil');
  Route::resource('/estimasi_bpd', \App\Http\Controllers\Estimasi_bpdController::class);
  Route::get('vestimasi_bp', [Estimasi_bpController::class, 'vestimasi_bp'])->name('vestimasi_bp');
  Route::get('estimasi_bpdajax', [Estimasi_bpController::class, 'estimasi_bpdajax'])->name('estimasi_bpdajax');
  Route::get('estimasi_bptambahdetail', [Estimasi_bpController::class, 'estimasi_bptambahdetail'])->name('estimasi_bptambahdetail');
  Route::get('estimasi_bptotaldetail', [Estimasi_bpController::class, 'estimasi_bptotaldetail'])->name('estimasi_bptotaldetail');
  Route::get('estimasi_bpinputestimasi_bpd', [Estimasi_bpController::class, 'estimasi_bpinputestimasi_bpd'])->name('estimasi_bpinputestimasi_bpd');
  Route::get('estimasi_bpdstore', [estimasi_bpdController::class, 'store'])->name('estimasi_bpdstore');
  Route::get('estimasi_bpdupdate', [estimasi_bpdController::class, 'update'])->name('update');
  Route::get('estimasi_bpcetak', [Estimasi_bpController::class, 'estimasi_bpcetak'])->name('estimasi_bpcetak');
  Route::get('estimasi_bpbatalproses', [Estimasi_bpController::class, 'estimasi_bpbatalproses'])->name('estimasi_bpbatalproses');
  Route::get('estimasi_bpbatalproseestimasi_bpk', [Estimasi_bpController::class, 'estimasi_bpbatalproseestimasi_bpk'])->name('estimasi_bpbatalprosesok');
  Route::get('tbljasa_estimasi_bpajax', [Estimasi_bpdController::class, 'tbljasa_estimasi_bpajax'])->name('tbljasa_estimasi_bpajax');
  Route::get('tblpart_estimasi_bpajax', [Estimasi_bpdController::class, 'tblpart_estimasi_bpajax'])->name('tblpart_estimasi_bpajax');
  Route::get('tblbahan_estimasi_bpajax', [Estimasi_bpdController::class, 'tblbahan_estimasi_bpajax'])->name('tblbahan_estimasi_bpajax');
  Route::get('tblopl_estimasi_bpajax', [Estimasi_bpdController::class, 'tblopl_estimasi_bpajax'])->name('tblopl_estimasi_bpajax');
  Route::get('summary_estimasi_bp', [Estimasi_bpdController::class, 'summary_estimasi_bp'])->name('summary_estimasi_bp');
  Route::get('cetak_estimasi_bp', [Estimasi_bpController::class, 'cetak_estimasi_bp'])->name('cetak_estimasi_bp');
  Route::post('buatwo_bp', [Estimasi_bpController::class, 'buatwo_bp'])->name('buatwo_bp');
  Route::get('wo_bpajax', [Estimasi_bpController::class, 'wo_bpajax'])->name('wo_bpajax');

  //WO Body Repair
  Route::resource('/wo_bp', \App\Http\Controllers\Wo_bpController::class);
  Route::resource('/wo_bpd', \App\Http\Controllers\Wo_bpdController::class);
  Route::get('detailwo_bp', [Wo_bpController::class, 'detailwo_bp'])->name('detailwo_bp');
  // Route::get('wo_bpedit', [Wo_bpController::class, 'wo_bpedit'])->name('wo_bpedit');
  Route::resource('/jasa_bp', \App\Http\Controllers\Jasa_bpController::class);
  Route::get('vwo_bp', [Wo_bpController::class, 'vwo_bp'])->name('vwo_bp');
  Route::get('vwo_bpajax', [Wo_bpController::class, 'vwo_bpajax'])->name('vwo_bpajax');
  Route::post('wo_bpproses', [Wo_bpController::class, 'wo_bpproses'])->name('wo_bpproses');
  Route::get('wo_bpunproses', [Wo_bpController::class, 'wo_bpunproses'])->name('wo_bpunproses');
  Route::post('wo_bpunproses_simpan', [Wo_bpController::class, 'wo_bpunproses_simpan'])->name('wo_bpunproses_simpan');
  Route::post('wo_bpcancel', [Wo_bpController::class, 'wo_bpcancel'])->name('wo_bpcancel');
  Route::post('wo_bpambil', [Wo_bpController::class, 'wo_bpambil'])->name('wo_bpambil');
  Route::get('vwojasa_bpajax', [Jasa_bpController::class, 'vwojasa_bpajax'])->name('vwojasa_bpajax');
  Route::get('jasa_bpdetail', [Jasa_bpController::class, 'jasa_bpdetail'])->name('jasa_bpdetail');
  Route::get('jasawo_bpajax', [Jasa_bpController::class, 'jasawo_bpajax'])->name('jasawo_bpajax');
  Route::resource('/part_bp', \App\Http\Controllers\Part_bpController::class);
  Route::get('vwopart_bpajax', [Part_bpController::class, 'vwopart_bpajax'])->name('vwopart_bpajax');
  Route::get('part_bpdetail', [Part_bpController::class, 'part_bpdetail'])->name('part_bpdetail');
  Route::get('partwo_bpajax', [Part_bpController::class, 'partwo_bpajax'])->name('partwo_bpajax');
  Route::get('proses_partwo_bp', [Part_bpController::class, 'proses_partwo_bp'])->name('proses_partwo_bp');
  Route::get('unproses_partwo_bp', [Part_bpController::class, 'unproses_partwo_bp'])->name('unproses_partwo_bp');
  Route::post('unproses_partwo_bp_simpan', [Part_bpController::class, 'unproses_partwo_bp_simpan'])->name('unproses_partwo_bp_simpan');
  Route::resource('/bahan_bp', \App\Http\Controllers\Bahan_bpController::class);
  Route::get('vwobahan_bpajax', [Bahan_bpController::class, 'vwobahan_bpajax'])->name('vwobahan_bpajax');
  Route::get('bahan_bpdetail', [Bahan_bpController::class, 'bahan_bpdetail'])->name('bahan_bpdetail');
  Route::get('bahanwo_bpajax', [Bahan_bpController::class, 'bahanwo_bpajax'])->name('bahanwo_bpajax');
  Route::get('proses_bahanwo_bp', [Bahan_bpController::class, 'proses_bahanwo_bp'])->name('proses_bahanwo_bp');
  Route::get('unproses_bahanwo_bp', [Bahan_bpController::class, 'unproses_bahanwo_bp'])->name('unproses_bahanwo_bp');
  Route::post('unproses_bahanwo_bp_simpan', [Bahan_bpController::class, 'unproses_bahanwo_bp_simpan'])->name('unproses_bahanwo_bp_simpan');
  Route::resource('/opl_bp', \App\Http\Controllers\Opl_bpController::class);
  Route::get('vwoopl_bpajax', [Opl_bpController::class, 'vwoopl_bpajax'])->name('vwoopl_bpajax');
  Route::get('opl_bpdetail', [Opl_bpController::class, 'opl_bpdetail'])->name('opl_bpdetail');
  Route::get('oplwo_bpajax', [Opl_bpController::class, 'oplwo_bpajax'])->name('oplwo_bpajax');
  Route::get('proses_oplwo_bp', [Opl_bpController::class, 'proses_oplwo_bp'])->name('proses_oplwo_bp');
  Route::get('unproses_oplwo_bp', [Opl_bpController::class, 'unproses_oplwo_bp'])->name('unproses_oplwo_bp');
  Route::post('unproses_oplwo_bp_simpan', [Opl_bpController::class, 'unproses_oplwo_bp_simpan'])->name('unproses_oplwo_bp_simpan');
  Route::get('summary_wo_bp', [Wo_bpController::class, 'summary_wo_bp'])->name('summary_wo_bp');
  Route::get('cetak_wo_bp', [wo_bpController::class, 'cetak_wo_bp'])->name('cetak_wo_bp');

  //Faktur Body Repair
  Route::resource('/faktur_bp', \App\Http\Controllers\Faktur_bpController::class);
  Route::get('faktur_bpajax', [Faktur_bpController::class, 'faktur_bpajax'])->name('faktur_bpajax');
  Route::resource('/faktur_bpd', \App\Http\Controllers\Faktur_bpdController::class);
  Route::get('detailfaktur_bp', [Faktur_bpController::class, 'detailfaktur_bp'])->name('detailfaktur_bp');
  // Route::get('wo_bpedit', [Faktur_bpController::class, 'wo_bpedit'])->name('wo_bpedit');
  Route::resource('/jasa_bp', \App\Http\Controllers\Jasa_bpController::class);
  Route::get('vfaktur_bp', [Faktur_bpController::class, 'vfaktur_bp'])->name('vfaktur_bp');
  Route::get('vfaktur_bpajax', [Faktur_bpController::class, 'vfaktur_bpajax'])->name('vfaktur_bpajax');
  Route::post('faktur_bpproses', [Faktur_bpController::class, 'faktur_bpproses'])->name('faktur_bpproses');
  Route::get('faktur_bpunproses', [Faktur_bpController::class, 'faktur_bpunproses'])->name('faktur_bpunproses');
  Route::post('faktur_bpunproses_simpan', [Faktur_bpController::class, 'faktur_bpunproses_simpan'])->name('faktur_bpunproses_simpan');
  Route::post('faktur_bpcancel', [Faktur_bpController::class, 'faktur_bpcancel'])->name('faktur_bpcancel');
  Route::post('faktur_bpambil', [Faktur_bpController::class, 'faktur_bpambil'])->name('faktur_bpambil');
  Route::get('vfakturjasa_bpajax', [Jasa_bpController::class, 'vfakturjasa_bpajax'])->name('vfakturjasa_bpajax');
  Route::get('jasa_bpdetail', [Jasa_bpController::class, 'jasa_bpdetail'])->name('jasa_bpdetail');
  Route::get('jasafaktur_bpajax', [Jasa_bpController::class, 'jasafaktur_bpajax'])->name('jasafaktur_bpajax');
  Route::resource('/part_bp', \App\Http\Controllers\Part_bpController::class);
  Route::get('vfakturpart_bpajax', [Part_bpController::class, 'vfakturpart_bpajax'])->name('vfakturpart_bpajax');
  Route::get('part_bpdetail', [Part_bpController::class, 'part_bpdetail'])->name('part_bpdetail');
  Route::get('partfaktur_bpajax', [Part_bpController::class, 'partfaktur_bpajax'])->name('partfaktur_bpajax');
  Route::get('proses_partfaktur_bp', [Part_bpController::class, 'proses_partfaktur_bp'])->name('proses_partfaktur_bp');
  Route::get('unproses_partfaktur_bp', [Part_bpController::class, 'unproses_partfaktur_bp'])->name('unproses_partfaktur_bp');
  Route::post('unproses_partfaktur_bp_simpan', [Part_bpController::class, 'unproses_partfaktur_bp_simpan'])->name('unproses_partfaktur_bp_simpan');
  Route::resource('/bahan_bp', \App\Http\Controllers\Bahan_bpController::class);
  Route::get('vfakturbahan_bpajax', [Bahan_bpController::class, 'vfakturbahan_bpajax'])->name('vfakturbahan_bpajax');
  Route::get('bahan_bpdetail', [Bahan_bpController::class, 'bahan_bpdetail'])->name('bahan_bpdetail');
  Route::get('bahanfaktur_bpajax', [Bahan_bpController::class, 'bahanfaktur_bpajax'])->name('bahanfaktur_bpajax');
  Route::get('proses_bahanfaktur_bp', [Bahan_bpController::class, 'proses_bahanfaktur_bp'])->name('proses_bahanfaktur_bp');
  Route::get('unproses_bahanfaktur_bp', [Bahan_bpController::class, 'unproses_bahanfaktur_bp'])->name('unproses_bahanfaktur_bp');
  Route::post('unproses_bahanfaktur_bp_simpan', [Bahan_bpController::class, 'unproses_bahanfaktur_bp_simpan'])->name('unproses_bahanfaktur_bp_simpan');
  Route::resource('/opl_bp', \App\Http\Controllers\Opl_bpController::class);
  Route::get('vfakturopl_bpajax', [Opl_bpController::class, 'vfakturopl_bpajax'])->name('vfakturopl_bpajax');
  Route::get('opl_bpdetail', [Opl_bpController::class, 'opl_bpdetail'])->name('opl_bpdetail');
  Route::get('oplfaktur_bpajax', [Opl_bpController::class, 'oplfaktur_bpajax'])->name('oplfaktur_bpajax');
  Route::get('proses_oplfaktur_bp', [Opl_bpController::class, 'proses_oplfaktur_bp'])->name('proses_oplfaktur_bp');
  Route::get('unproses_oplfaktur_bp', [Opl_bpController::class, 'unproses_oplfaktur_bp'])->name('unproses_oplfaktur_bp');
  Route::post('unproses_oplfaktur_bp_simpan', [Opl_bpController::class, 'unproses_oplfaktur_bp_simpan'])->name('unproses_oplfaktur_bp_simpan');
  Route::get('summary_faktur_bp', [Faktur_bpdController::class, 'summary_faktur_bp'])->name('summary_faktur_bp');
  Route::get('cetak_faktur_bp', [Faktur_bpController::class, 'cetak_faktur_bp'])->name('cetak_faktur_bp');

  //Estimasi WO General Repair
  Route::resource('/estimasi_gr', \App\Http\Controllers\Estimasi_grController::class);
  Route::get('estimasi_gr', [Estimasi_grController::class, 'index'])->name('index');
  Route::get('tbmobil_grajax', [Estimasi_grController::class, 'tbmobil_grajax'])->name('tbmobil_grajax');
  Route::post('tbmobil_update', [Estimasi_grController::class, 'tbmobil_update'])->name('tbmobil_update');
  Route::post('estimasi_gr_create', [Estimasi_grController::class, 'estimasi_gr_create'])->name('estimasi_gr_create');
  Route::post('estimasi_gr_tambah', [Estimasi_grController::class, 'estimasi_gr_tambah'])->name('estimasi_gr_tambah');
  Route::post('estimasi_gr_edit', [Estimasi_grController::class, 'estimasi_gr_create'])->name('estimasi_gr_create');
  // Route::post('estimasi_gr_update', [Estimasi_grController::class, 'estimasi_gr_update'])->name('estimasi_gr_simpan');
  Route::resource('/tbmobil_gr', \App\Http\Controllers\Estimasi_grController::class);
  Route::get('estimasi_grajax', [Estimasi_grController::class, 'estimasi_grajax'])->name('estimasi_grajax');
  Route::get('estimasi_grupdate', [Estimasi_grController::class, 'update'])->name('update');
  Route::get('detailestimasi_gr', [Estimasi_grController::class, 'detailestimasi_gr'])->name('detailestimasi_gr');
  Route::post('estimasi_grproses', [Estimasi_grController::class, 'estimasi_grproses'])->name('estimasi_grproses');
  Route::get('estimasi_grunproses', [Estimasi_grController::class, 'estimasi_grunproses'])->name('estimasi_grunproses');
  Route::post('estimasi_grunproses_simpan', [Estimasi_grController::class, 'estimasi_grunproses_simpan'])->name('estimasi_grunproses_simpan');
  Route::post('estimasi_grcancel', [Estimasi_grController::class, 'estimasi_grcancel'])->name('estimasi_grcancel');
  Route::post('estimasi_grambil', [Estimasi_grController::class, 'estimasi_grambil'])->name('estimasi_grambil');
  Route::resource('/estimasi_grd', \App\Http\Controllers\Estimasi_grdController::class);
  Route::get('vestimasi_gr', [Estimasi_grController::class, 'vestimasi_gr'])->name('vestimasi_gr');
  Route::get('estimasi_grdajax', [Estimasi_grController::class, 'estimasi_grdajax'])->name('estimasi_grdajax');
  Route::get('estimasi_grtambahdetail', [Estimasi_grController::class, 'estimasi_grtambahdetail'])->name('estimasi_grtambahdetail');
  Route::get('estimasi_grtotaldetail', [Estimasi_grController::class, 'estimasi_grtotaldetail'])->name('estimasi_grtotaldetail');
  Route::get('estimasi_grinputestimasi_grd', [Estimasi_grController::class, 'estimasi_grinputestimasi_grd'])->name('estimasi_grinputestimasi_grd');
  Route::get('estimasi_grdstore', [estimasi_grdController::class, 'store'])->name('estimasi_grdstore');
  Route::get('estimasi_grdupdate', [estimasi_grdController::class, 'update'])->name('update');
  Route::get('estimasi_grcetak', [Estimasi_grController::class, 'estimasi_grcetak'])->name('estimasi_grcetak');
  Route::get('estimasi_grbatalproses', [Estimasi_grController::class, 'estimasi_grbatalproses'])->name('estimasi_grbatalproses');
  Route::get('estimasi_grbatalproseestimasi_grk', [Estimasi_grController::class, 'estimasi_grbatalproseestimasi_grk'])->name('estimasi_grbatalprosesok');
  Route::get('tbljasa_estimasi_grajax', [Estimasi_grdController::class, 'tbljasa_estimasi_grajax'])->name('tbljasa_estimasi_grajax');
  Route::get('tblpart_estimasi_grajax', [Estimasi_grdController::class, 'tblpart_estimasi_grajax'])->name('tblpart_estimasi_grajax');
  Route::get('tblbahan_estimasi_grajax', [Estimasi_grdController::class, 'tblbahan_estimasi_grajax'])->name('tblbahan_estimasi_grajax');
  Route::get('tblopl_estimasi_grajax', [Estimasi_grdController::class, 'tblopl_estimasi_grajax'])->name('tblopl_estimasi_grajax');
  Route::get('summary_estimasi_gr', [Estimasi_grdController::class, 'summary_estimasi_gr'])->name('summary_estimasi_gr');
  Route::get('cetak_estimasi_gr', [Estimasi_grController::class, 'cetak_estimasi_gr'])->name('cetak_estimasi_gr');
  Route::post('buatwo_gr', [Estimasi_grController::class, 'buatwo_gr'])->name('buatwo_gr');
  Route::get('wo_grajax', [Estimasi_grController::class, 'wo_grajax'])->name('wo_grajax');

  //WO General Repair
  Route::resource('/wo_gr', \App\Http\Controllers\Wo_grController::class);
  Route::resource('/wo_grd', \App\Http\Controllers\Wo_grdController::class);
  Route::get('detailwo_gr', [Wo_grController::class, 'detailwo_gr'])->name('detailwo_gr');
  // Route::get('wo_gredit', [Wo_grController::class, 'wo_gredit'])->name('wo_gredit');
  Route::resource('/jasa_gr', \App\Http\Controllers\Jasa_grController::class);
  Route::get('vwo_gr', [Wo_grController::class, 'vwo_gr'])->name('vwo_gr');
  Route::get('vwo_grajax', [Wo_grController::class, 'vwo_grajax'])->name('vwo_grajax');
  Route::post('wo_grproses', [Wo_grController::class, 'wo_grproses'])->name('wo_grproses');
  Route::get('wo_grunproses', [Wo_grController::class, 'wo_grunproses'])->name('wo_grunproses');
  Route::post('wo_grunproses_simpan', [Wo_grController::class, 'wo_grunproses_simpan'])->name('wo_grunproses_simpan');
  Route::post('wo_grcancel', [Wo_grController::class, 'wo_grcancel'])->name('wo_grcancel');
  Route::post('wo_grambil', [Wo_grController::class, 'wo_grambil'])->name('wo_grambil');
  Route::get('vwojasa_grajax', [Jasa_grController::class, 'vwojasa_grajax'])->name('vwojasa_grajax');
  Route::get('jasa_grdetail', [Jasa_grController::class, 'jasa_grdetail'])->name('jasa_grdetail');
  Route::get('jasawo_grajax', [Jasa_grController::class, 'jasawo_grajax'])->name('jasawo_grajax');
  Route::resource('/part_gr', \App\Http\Controllers\Part_grController::class);
  Route::get('vwopart_grajax', [Part_grController::class, 'vwopart_grajax'])->name('vwopart_grajax');
  Route::get('part_grdetail', [Part_grController::class, 'part_grdetail'])->name('part_grdetail');
  Route::get('partwo_grajax', [Part_grController::class, 'partwo_grajax'])->name('partwo_grajax');
  Route::get('proses_partwo_gr', [Part_grController::class, 'proses_partwo_gr'])->name('proses_partwo_gr');
  Route::get('unproses_partwo_gr', [Part_grController::class, 'unproses_partwo_gr'])->name('unproses_partwo_gr');
  Route::post('unproses_partwo_gr_simpan', [Part_grController::class, 'unproses_partwo_gr_simpan'])->name('unproses_partwo_gr_simpan');
  Route::resource('/bahan_gr', \App\Http\Controllers\Bahan_grController::class);
  Route::get('vwobahan_grajax', [Bahan_grController::class, 'vwobahan_grajax'])->name('vwobahan_grajax');
  Route::get('bahan_grdetail', [Bahan_grController::class, 'bahan_grdetail'])->name('bahan_grdetail');
  Route::get('bahanwo_grajax', [Bahan_grController::class, 'bahanwo_grajax'])->name('bahanwo_grajax');
  Route::get('proses_bahanwo_gr', [Bahan_grController::class, 'proses_bahanwo_gr'])->name('proses_bahanwo_gr');
  Route::get('unproses_bahanwo_gr', [Bahan_grController::class, 'unproses_bahanwo_gr'])->name('unproses_bahanwo_gr');
  Route::post('unproses_bahanwo_gr_simpan', [Bahan_grController::class, 'unproses_bahanwo_gr_simpan'])->name('unproses_bahanwo_gr_simpan');
  Route::resource('/opl_gr', \App\Http\Controllers\Opl_grController::class);
  Route::get('vwoopl_grajax', [Opl_grController::class, 'vwoopl_grajax'])->name('vwoopl_grajax');
  Route::get('opl_grdetail', [Opl_grController::class, 'opl_grdetail'])->name('opl_grdetail');
  Route::get('oplwo_grajax', [Opl_grController::class, 'oplwo_grajax'])->name('oplwo_grajax');
  Route::get('proses_oplwo_gr', [Opl_grController::class, 'proses_oplwo_gr'])->name('proses_oplwo_gr');
  Route::get('unproses_oplwo_gr', [Opl_grController::class, 'unproses_oplwo_gr'])->name('unproses_oplwo_gr');
  Route::post('unproses_oplwo_gr_simpan', [Opl_grController::class, 'unproses_oplwo_gr_simpan'])->name('unproses_oplwo_gr_simpan');
  Route::get('summary_wo_gr', [Wo_grController::class, 'summary_wo_gr'])->name('summary_wo_gr');
  Route::get('cetak_wo_gr', [wo_grController::class, 'cetak_wo_gr'])->name('cetak_wo_gr');

  //Faktur Body Repair
  Route::resource('/faktur_gr', \App\Http\Controllers\Faktur_grController::class);
  Route::get('faktur_grajax', [Faktur_grController::class, 'faktur_grajax'])->name('faktur_grajax');
  Route::resource('/faktur_grd', \App\Http\Controllers\Faktur_grdController::class);
  Route::get('detailfaktur_gr', [Faktur_grController::class, 'detailfaktur_gr'])->name('detailfaktur_gr');
  // Route::get('wo_gredit', [Faktur_grController::class, 'wo_gredit'])->name('wo_gredit');
  Route::resource('/jasa_gr', \App\Http\Controllers\Jasa_grController::class);
  Route::get('vfaktur_gr', [Faktur_grController::class, 'vfaktur_gr'])->name('vfaktur_gr');
  Route::get('vfaktur_grajax', [Faktur_grController::class, 'vfaktur_grajax'])->name('vfaktur_grajax');
  Route::post('faktur_grproses', [Faktur_grController::class, 'faktur_grproses'])->name('faktur_grproses');
  Route::get('faktur_grunproses', [Faktur_grController::class, 'faktur_grunproses'])->name('faktur_grunproses');
  Route::post('faktur_grunproses_simpan', [Faktur_grController::class, 'faktur_grunproses_simpan'])->name('faktur_grunproses_simpan');
  Route::post('faktur_grcancel', [Faktur_grController::class, 'faktur_grcancel'])->name('faktur_grcancel');
  Route::post('faktur_grambil', [Faktur_grController::class, 'faktur_grambil'])->name('faktur_grambil');
  Route::get('vfakturjasa_grajax', [Jasa_grController::class, 'vfakturjasa_grajax'])->name('vfakturjasa_grajax');
  Route::get('jasa_grdetail', [Jasa_grController::class, 'jasa_grdetail'])->name('jasa_grdetail');
  Route::get('jasafaktur_grajax', [Jasa_grController::class, 'jasafaktur_grajax'])->name('jasafaktur_grajax');
  Route::resource('/part_gr', \App\Http\Controllers\Part_grController::class);
  Route::get('vfakturpart_grajax', [Part_grController::class, 'vfakturpart_grajax'])->name('vfakturpart_grajax');
  Route::get('part_grdetail', [Part_grController::class, 'part_grdetail'])->name('part_grdetail');
  Route::get('partfaktur_grajax', [Part_grController::class, 'partfaktur_grajax'])->name('partfaktur_grajax');
  Route::get('proses_partfaktur_gr', [Part_grController::class, 'proses_partfaktur_gr'])->name('proses_partfaktur_gr');
  Route::get('unproses_partfaktur_gr', [Part_grController::class, 'unproses_partfaktur_gr'])->name('unproses_partfaktur_gr');
  Route::post('unproses_partfaktur_gr_simpan', [Part_grController::class, 'unproses_partfaktur_gr_simpan'])->name('unproses_partfaktur_gr_simpan');
  Route::resource('/bahan_gr', \App\Http\Controllers\Bahan_grController::class);
  Route::get('vfakturbahan_grajax', [Bahan_grController::class, 'vfakturbahan_grajax'])->name('vfakturbahan_grajax');
  Route::get('bahan_grdetail', [Bahan_grController::class, 'bahan_grdetail'])->name('bahan_grdetail');
  Route::get('bahanfaktur_grajax', [Bahan_grController::class, 'bahanfaktur_grajax'])->name('bahanfaktur_grajax');
  Route::get('proses_bahanfaktur_gr', [Bahan_grController::class, 'proses_bahanfaktur_gr'])->name('proses_bahanfaktur_gr');
  Route::get('unproses_bahanfaktur_gr', [Bahan_grController::class, 'unproses_bahanfaktur_gr'])->name('unproses_bahanfaktur_gr');
  Route::post('unproses_bahanfaktur_gr_simpan', [Bahan_grController::class, 'unproses_bahanfaktur_gr_simpan'])->name('unproses_bahanfaktur_gr_simpan');
  Route::resource('/opl_gr', \App\Http\Controllers\Opl_grController::class);
  Route::get('vfakturopl_grajax', [Opl_grController::class, 'vfakturopl_grajax'])->name('vfakturopl_grajax');
  Route::get('opl_grdetail', [Opl_grController::class, 'opl_grdetail'])->name('opl_grdetail');
  Route::get('oplfaktur_grajax', [Opl_grController::class, 'oplfaktur_grajax'])->name('oplfaktur_grajax');
  Route::get('proses_oplfaktur_gr', [Opl_grController::class, 'proses_oplfaktur_gr'])->name('proses_oplfaktur_gr');
  Route::get('unproses_oplfaktur_gr', [Opl_grController::class, 'unproses_oplfaktur_gr'])->name('unproses_oplfaktur_gr');
  Route::post('unproses_oplfaktur_gr_simpan', [Opl_grController::class, 'unproses_oplfaktur_gr_simpan'])->name('unproses_oplfaktur_gr_simpan');
  Route::get('summary_faktur_gr', [Faktur_grdController::class, 'summary_faktur_gr'])->name('summary_faktur_gr');
  Route::get('cetak_faktur_gr', [Faktur_grController::class, 'cetak_faktur_gr'])->name('cetak_faktur_gr');

  // Route::get('caricustomer', [SoController::class, 'caricustomer'])->name('caricustomer');
  // Route::get('replcustomer', [SoController::class, 'replcustomer'])->name('replcustomer');
  // Route::get('carisales', [SoController::class, 'carisales'])->name('carisales');
  // Route::get('replsales', [SoController::class, 'replsales'])->name('replsales');
  // Route::get('socaritbbarang', [SoController::class, 'socaritbbarang'])->name('socaritbbarang');
  // Route::get('sorepltbbarang', [SoController::class, 'sorepltbbarang'])->name('sorepltbbarang');
  // Route::get('socaritbmultiprc', [SoController::class, 'socaritbmultiprc'])->name('socaritbmultiprc');
  // Route::get('sorepltbmultiprc', [SoController::class, 'sorepltbmultiprc'])->name('sorepltbmultiprc');
  //Sales Order
  Route::resource('/so', \App\Http\Controllers\SoController::class);
  Route::get('soajax', [SoController::class, 'soajax'])->name('soajax');
  Route::get('soupdate', [SoController::class, 'update'])->name('update');
  Route::post('soproses/{soproses}', [SoController::class, 'soproses'])->name('soproses');
  Route::post('sounproses', [SoController::class, 'sounproses'])->name('sounproses');
  Route::post('socancel', [SoController::class, 'socancel'])->name('socancel');
  Route::post('soambil', [SoController::class, 'soambil'])->name('soambil');
  Route::resource('/sod', \App\Http\Controllers\SodController::class);
  Route::get('sodajax', [SoController::class, 'sodajax'])->name('sodajax');
  Route::get('sotambahdetail', [SoController::class, 'sotambahdetail'])->name('sotambahdetail');
  Route::get('sototaldetail', [SoController::class, 'sototaldetail'])->name('sototaldetail');
  Route::get('soinputsod', [SoController::class, 'soinputsod'])->name('soinputsod');
  Route::get('sodstore', [SodController::class, 'store'])->name('sodstore');
  Route::get('sodupdate', [SodController::class, 'update'])->name('update');
  Route::get('socetak', [SoController::class, 'socetak'])->name('socetak');
  Route::get('sobatalproses', [SoController::class, 'sobatalproses'])->name('sobatalproses');
  Route::get('sobatalprosesok', [SoController::class, 'sobatalprosesok'])->name('sobatalprosesok');
  //Penjualan
  Route::resource('/jual', \App\Http\Controllers\JualController::class);
  Route::get('jualajax', [JualController::class, 'jualajax'])->name('jualajax');
  Route::get('jualupdate', [JualController::class, 'update'])->name('update');
  Route::post('jualproses/{jualproses}', [JualController::class, 'jualproses'])->name('jualproses');
  Route::post('jualunproses', [JualController::class, 'jualunproses'])->name('jualunproses');
  Route::post('Jualcancel', [JualController::class, 'Jualcancel'])->name('Jualcancel');
  Route::post('jualambil', [JualController::class, 'jualambil'])->name('jualambil');
  Route::resource('/juald', \App\Http\Controllers\JualdController::class);
  Route::get('jualdajax', [JualController::class, 'jualdajax'])->name('jualdajax');
  Route::get('cariso', [JualController::class, 'cariso'])->name('cariso');
  Route::get('replso', [JualController::class, 'replso'])->name('replso');
  Route::get('prosessalinso', [JualController::class, 'prosessalinso'])->name('prosessalinso');
  Route::get('jualtambahdetail', [JualController::class, 'jualtambahdetail'])->name('jualtambahdetail');
  Route::get('jualtotaldetail', [JualController::class, 'jualtotaldetail'])->name('jualtotaldetail');
  Route::get('jualinputjuald', [JualController::class, 'jualinputjuald'])->name('jualinputjuald');
  Route::get('jualdstore', [JualdController::class, 'store'])->name('jualdstore');
  Route::get('jualdupdate', [JualdController::class, 'update'])->name('update');
  Route::get('jualcetakfp', [JualController::class, 'jualcetakfp'])->name('jualcetakfp');
  Route::get('jualcetaksj', [JualController::class, 'jualcetaksj'])->name('jualcetaksj');
  Route::get('jualbatalproses', [JualController::class, 'jualbatalproses'])->name('jualbatalproses');
  Route::get('jualbatalprosesok', [JualController::class, 'jualbatalprosesok'])->name('jualbatalprosesok');
  //Purchase Order
  Route::resource('/po', \App\Http\Controllers\PoController::class);
  Route::get('poajax', [PoController::class, 'poajax'])->name('poajax');
  Route::get('poupdate', [PoController::class, 'update'])->name('update');
  Route::post('poproses/{poproses}', [PoController::class, 'poproses'])->name('poproses');
  Route::post('pounproses', [PoController::class, 'pounproses'])->name('pounproses');
  Route::post('pocancel', [PoController::class, 'pocancel'])->name('pocancel');
  Route::post('poambil', [PoController::class, 'poambil'])->name('poambil');
  Route::resource('/pod', \App\Http\Controllers\PodController::class);
  Route::get('podajax', [PoController::class, 'podajax'])->name('podajax');
  Route::get('potambahdetail', [PoController::class, 'potambahdetail'])->name('potambahdetail');
  Route::get('pototaldetail', [PoController::class, 'pototaldetail'])->name('pototaldetail');
  Route::get('poinputpod', [PoController::class, 'poinputpod'])->name('poinputpod');
  Route::get('podstore', [PodController::class, 'store'])->name('podstore');
  Route::get('podupdate', [PodController::class, 'update'])->name('update');
  Route::get('pocetak', [PoController::class, 'pocetak'])->name('pocetak');
  Route::get('pobatalproses', [PoController::class, 'pobatalproses'])->name('pobatalproses');
  Route::get('pobatalprosesok', [PoController::class, 'pobatalprosesok'])->name('pobatalprosesok');
  //Pembelian
  Route::resource('/beli', \App\Http\Controllers\BeliController::class);
  Route::get('beliajax', [BeliController::class, 'beliajax'])->name('beliajax');
  Route::get('beliupdate', [BeliController::class, 'update'])->name('update');
  Route::post('beliproses/{beliproses}', [BeliController::class, 'beliproses'])->name('beliproses');
  Route::post('beliunproses', [BeliController::class, 'beliunproses'])->name('beliunproses');
  Route::post('belicancel', [BeliController::class, 'belicancel'])->name('belicancel');
  Route::post('beliambil', [BeliController::class, 'beliambil'])->name('beliambil');
  Route::resource('/belid', \App\Http\Controllers\BelidController::class);
  Route::get('belidajax', [BeliController::class, 'belidajax'])->name('belidajax');
  Route::get('carigudang', [BeliController::class, 'carigudang'])->name('carigudang');
  Route::get('replgudang', [BeliController::class, 'replgudang'])->name('replgudang');
  Route::get('caripo', [BeliController::class, 'caripo'])->name('caripo');
  Route::get('replpo', [BeliController::class, 'replpo'])->name('replpo');
  Route::get('prosessalinpo', [BeliController::class, 'prosessalinpo'])->name('prosessalinpo');
  Route::get('belitambahdetail', [BeliController::class, 'belitambahdetail'])->name('belitambahdetail');
  Route::get('belitotaldetail', [BeliController::class, 'belitotaldetail'])->name('belitotaldetail');
  Route::get('beliinputbelid', [BeliController::class, 'beliinputbelid'])->name('beliinputbelid');
  Route::get('belidstore', [BelidController::class, 'store'])->name('belidstore');
  Route::get('belidupdate', [BelidController::class, 'update'])->name('update');
  Route::get('belicetak', [BeliController::class, 'belicetak'])->name('belicetak');
  Route::get('belibatalproses', [BeliController::class, 'belibatalproses'])->name('belibatalproses');
  Route::get('belibatalprosesok', [BeliController::class, 'belibatalprosesok'])->name('belibatalprosesok');
  //Penerimaan Barang
  Route::resource('/terima', \App\Http\Controllers\TerimaController::class);
  Route::get('terimaajax', [TerimaController::class, 'terimaajax'])->name('terimaajax');
  Route::get('ambildatatbjntranst', [TerimaController::class, 'ambildatatbjntranst'])->name('ambildatatbjntranst');
  Route::get('carikdjntrans', [TerimaController::class, 'carikdjntrans'])->name('carikdjntrans');
  Route::get('terimaupdate', [TerimaController::class, 'update'])->name('update');
  Route::post('terimaproses/{terimaproses}', [TerimaController::class, 'terimaproses'])->name('terimaproses');
  Route::post('terimaunproses', [TerimaController::class, 'terimaunproses'])->name('terimaunproses');
  Route::post('terimacancel', [TerimaController::class, 'terimacancel'])->name('terimacancel');
  Route::post('terimaambil', [TerimaController::class, 'terimaambil'])->name('terimaambil');
  Route::resource('/terimad', \App\Http\Controllers\TerimadController::class);
  Route::get('terimadajax', [TerimaController::class, 'terimadajax'])->name('terimadajax');
  Route::get('terimatambahdetail', [TerimaController::class, 'terimatambahdetail'])->name('terimatambahdetail');
  Route::get('terimatotaldetail', [TerimaController::class, 'terimatotaldetail'])->name('terimatotaldetail');
  Route::get('terimainputterimad', [TerimaController::class, 'terimainputterimad'])->name('terimainputterimad');
  Route::get('terimadstore', [TerimadController::class, 'store'])->name('terimadstore');
  Route::get('terimadupdate', [TerimadController::class, 'update'])->name('update');
  Route::get('terimacetak', [TerimaController::class, 'terimacetak'])->name('terimacetak');
  Route::get('terimabatalproses', [TerimaController::class, 'terimabatalproses'])->name('terimabatalproses');
  Route::get('terimabatalprosesok', [TerimaController::class, 'terimabatalprosesok'])->name('terimabatalprosesok');
  //Pengeluaran Barang
  Route::resource('/keluar', \App\Http\Controllers\KeluarController::class);
  Route::get('keluarajax', [KeluarController::class, 'keluarajax'])->name('keluarajax');
  Route::get('ambildatatbjntransk', [KeluarController::class, 'ambildatatbjntransk'])->name('ambildatatbjntransk');
  Route::get('carikdjntrans', [KeluarController::class, 'carikdjntrans'])->name('carikdjntrans');
  Route::get('keluarupdate', [KeluarController::class, 'update'])->name('update');
  Route::post('keluarproses/{keluarproses}', [KeluarController::class, 'keluarproses'])->name('keluarproses');
  Route::post('keluarunproses', [KeluarController::class, 'keluarunproses'])->name('keluarunproses');
  Route::post('keluarcancel', [KeluarController::class, 'keluarcancel'])->name('keluarcancel');
  Route::post('keluarambil', [KeluarController::class, 'keluarambil'])->name('keluarambil');
  Route::resource('/keluard', \App\Http\Controllers\KeluardController::class);
  Route::get('keluardajax', [KeluarController::class, 'keluardajax'])->name('keluardajax');
  Route::get('keluartambahdetail', [KeluarController::class, 'keluartambahdetail'])->name('keluartambahdetail');
  Route::get('keluartotaldetail', [KeluarController::class, 'keluartotaldetail'])->name('keluartotaldetail');
  Route::get('keluarinputkeluard', [KeluarController::class, 'keluarinputkeluard'])->name('keluarinputkeluard');
  Route::get('keluardstore', [KeluardController::class, 'store'])->name('keluardstore');
  Route::get('keluardupdate', [KeluardController::class, 'update'])->name('update');
  Route::get('keluarcetak', [KeluarController::class, 'keluarCetak'])->name('keluarcetak');
  Route::get('keluarbatalproses', [KeluarController::class, 'keluarbatalproses'])->name('keluarbatalproses');
  Route::get('keluarbatalprosesok', [KeluarController::class, 'keluarbatalprosesok'])->name('keluarbatalprosesok');
  //Stock Opname
  Route::resource('/opname', \App\Http\Controllers\OpnameController::class);
  Route::get('opnameajax', [OpnameController::class, 'opnameajax'])->name('opnameajax');
  Route::get('opnameupdate', [OpnameController::class, 'update'])->name('update');
  Route::post('opnamesalinbarang/{opnamesalinbarang}', [OpnameController::class, 'opnamesalinbarang'])->name('opnamesalinbarang');
  Route::post('opnameproses/{opnameproses}', [OpnameController::class, 'opnameproses'])->name('opnameproses');
  Route::post('opnameunproses', [OpnameController::class, 'opnameunproses'])->name('opnameunproses');
  Route::post('opnamecancel', [OpnameController::class, 'opnamecancel'])->name('opnamecancel');
  Route::post('opnameambil', [OpnameController::class, 'opnameambil'])->name('opnameambil');
  Route::resource('/opnamed', \App\Http\Controllers\OpnamedController::class);
  Route::get('opnamedajax', [OpnameController::class, 'opnamedajax'])->name('opnamedajax');
  Route::get('opnametambahdetail', [OpnameController::class, 'opnametambahdetail'])->name('opnametambahdetail');
  Route::get('opnametotaldetail', [OpnameController::class, 'opnametotaldetail'])->name('opnametotaldetail');
  Route::get('opnameinputopnamed', [OpnameController::class, 'opnameinputopnamed'])->name('opnameinputopnamed');
  Route::get('opnamedstore', [OpnamedController::class, 'store'])->name('opnamedstore');
  Route::get('opnamedupdate', [OpnamedController::class, 'update'])->name('update');
  Route::get('opnamecetak', [OpnameController::class, 'opnameCetak'])->name('opnamecetak');
  Route::get('opnamebatalproses', [OpnameController::class, 'opnamebatalproses'])->name('opnamebatalproses');
  Route::get('opnamebatalprosesok', [OpnameController::class, 'opnamebatalprosesok'])->name('opnamebatalprosesok');
  //Approv batas piutang
  Route::resource('/approv_batas_piutang', \App\Http\Controllers\Approv_batas_piutangController::class);
  Route::get('approv_batas_piutangajax', [Approv_batas_piutangController::class, 'approv_batas_piutangajax'])->name('approv_batas_piutangajax');
  Route::get('approv_batas_piutangupdate', [Approv_batas_piutangController::class, 'update'])->name('update');
  Route::post('approv_batas_piutangproses/{approv_batas_piutangproses}', [Approv_batas_piutangController::class, 'approv_batas_piutangproses'])->name('approv_batas_piutangproses');
  Route::post('approv_batas_piutangunproses', [Approv_batas_piutangController::class, 'approv_batas_piutangunproses'])->name('approv_batas_piutangunproses');
  Route::post('approv_batas_piutangcancel', [Approv_batas_piutangController::class, 'approv_batas_piutangcancel'])->name('approv_batas_piutangcancel');
  Route::post('approv_batas_piutangambil', [Approv_batas_piutangController::class, 'approv_batas_piutangambil'])->name('approv_batas_piutangambil');
  Route::get('approv_batas_piutangcetak', [Approv_batas_piutangController::class, 'approv_batas_piutangCetak'])->name('approv_batas_piutangcetak');
  Route::get('approv_batas_piutangbatalproses', [Approv_batas_piutangController::class, 'approv_batas_piutangbatalproses'])->name('approv_batas_piutangbatalproses');
  Route::get('approv_batas_piutangbatalprosesok', [Approv_batas_piutangController::class, 'approv_batas_piutangbatalprosesok'])->name('approv_batas_piutangbatalprosesok');
  //Kasir tunai
  Route::resource('/kasir_tunai', \App\Http\Controllers\Kasir_tunaiController::class);
  Route::get('kasir_tunaiajax', [Kasir_tunaiController::class, 'kasir_tunaiajax'])->name('kasir_tunaiajax');
  Route::get('kasir_tunaiupdate', [Kasir_tunaiController::class, 'update'])->name('update');
  Route::post('kasir_tunaiproses/{kasir_tunaiproses}', [Kasir_tunaiController::class, 'kasir_tunaiproses'])->name('kasir_tunaiproses');
  Route::post('kasir_tunaiunproses', [Kasir_tunaiController::class, 'kasir_tunaiunproses'])->name('kasir_tunaiunproses');
  Route::post('kasir_tunaicancel', [Kasir_tunaiController::class, 'kasir_tunaicancel'])->name('kasir_tunaicancel');
  Route::post('kasir_tunaiambil', [Kasir_tunaiController::class, 'kasir_tunaiambil'])->name('kasir_tunaiambil');
  Route::get('kasir_tunaicetak', [Kasir_tunaiController::class, 'kasir_tunaiCetak'])->name('kasir_tunaicetak');
  Route::get('kasir_tunaibatalproses', [Kasir_tunaiController::class, 'kasir_tunaibatalproses'])->name('kasir_tunaibatalproses');
  Route::get('kasir_tunaibatalprosesok', [Kasir_tunaiController::class, 'kasir_tunaibatalprosesok'])->name('kasir_tunaibatalprosesok');
  //Kasir tagihan
  Route::resource('/kasir_tagihan', \App\Http\Controllers\Kasir_tagihanController::class);
  Route::get('kasir_tagihanajax', [Kasir_tagihanController::class, 'kasir_tagihanajax'])->name('kasir_tagihanajax');
  Route::get('kasir_tagihanupdate', [Kasir_tagihanController::class, 'update'])->name('update');
  Route::resource('/kasir_tagihand', \App\Http\Controllers\Kasir_tagihandController::class);
  Route::get('kasir_tagihandajax', [Kasir_tagihandController::class, 'kasir_tagihandajax'])->name('kasir_tagihandajax');
  Route::get('kasir_tagihantambahdetail', [Kasir_tagihandController::class, 'kasir_tagihantambahdetail'])->name('kasir_tagihantambahdetail');
  Route::get('kasir_tagihantotaldetail', [Kasir_tagihandController::class, 'kasir_tagihantotaldetail'])->name('kasir_tagihantotaldetail');
  Route::get('kasir_tagihaninputkasir_tagihand', [Kasir_tagihandController::class, 'kasir_tagihaninputkasir_tagihand'])->name('kasir_tagihaninputkasir_tagihand');
  Route::get('kasir_tagihandstore', [Kasir_tagihandController::class, 'store'])->name('kasir_tagihandstore');
  Route::get('kasir_tagihandupdate', [Kasir_tagihandController::class, 'update'])->name('update');
  Route::post('kasir_tagihanproses/{kasir_tagihanproses}', [Kasir_tagihanController::class, 'kasir_tagihanproses'])->name('kasir_tagihanproses');
  Route::post('kasir_tagihanunproses', [Kasir_tagihanController::class, 'kasir_tagihanunproses'])->name('kasir_tagihanunproses');
  Route::post('kasir_tagihancancel', [Kasir_tagihanController::class, 'kasir_tagihancancel'])->name('kasir_tagihancancel');
  Route::post('kasir_tagihanambil', [Kasir_tagihanController::class, 'kasir_tagihanambil'])->name('kasir_tagihanambil');
  Route::get('kasir_tagihancetak', [Kasir_tagihanController::class, 'kasir_tagihanCetak'])->name('kasir_tagihancetak');
  Route::get('kasir_tagihanbatalproses', [Kasir_tagihanController::class, 'kasir_tagihanbatalproses'])->name('kasir_tagihanbatalproses');
  Route::get('kasir_tagihanbatalprosesok', [Kasir_tagihanController::class, 'kasir_tagihanbatalprosesok'])->name('kasir_tagihanbatalprosesok');
  //Permohonan Keluar Uang
  Route::resource('/mohklruang', \App\Http\Controllers\MohklruangController::class);
  Route::get('mohklruangajax', [MohklruangController::class, 'mohklruangajax'])->name('mohklruangajax');
  Route::get('ambildatatbjnkeluar', [MohklruangController::class, 'ambildatatbjnkeluar'])->name('ambildatatbjnkeluar');
  Route::get('carikdjnkeluar', [MohklruangController::class, 'carikdjnkeluar'])->name('carikdjnkeluar');
  Route::get('mohklruangupdate', [MohklruangController::class, 'update'])->name('update');
  Route::resource('/mohklruangd', \App\Http\Controllers\MohklruangdController::class);
  Route::get('mohklruangdajax', [MohklruangdController::class, 'mohklruangdajax'])->name('mohklruangdajax');
  Route::get('mohklruangtambahdetail', [MohklruangdController::class, 'mohklruangtambahdetail'])->name('mohklruangtambahdetail');
  Route::get('mohklruangtotaldetail', [MohklruangdController::class, 'mohklruangtotaldetail'])->name('mohklruangtotaldetail');
  Route::get('mohklruanginputmohklruangd', [MohklruangdController::class, 'mohklruanginputmohklruangd'])->name('mohklruanginputmohklruangd');
  Route::get('mohklruangdstore', [MohklruangdController::class, 'store'])->name('mohklruangdstore');
  Route::get('mohklruangdupdate', [MohklruangdController::class, 'update'])->name('update');
  Route::post('mohklruangproses/{mohklruangproses}', [MohklruangController::class, 'mohklruangproses'])->name('mohklruangproses');
  Route::post('mohklruangunproses', [MohklruangController::class, 'mohklruangunproses'])->name('mohklruangunproses');
  Route::post('mohklruangcancel', [MohklruangController::class, 'mohklruangcancel'])->name('mohklruangcancel');
  Route::post('mohklruangambil', [MohklruangController::class, 'mohklruangambil'])->name('mohklruangambil');
  Route::get('mohklruangcetak', [MohklruangController::class, 'mohklruangCetak'])->name('mohklruangcetak');
  Route::get('mohklruangbatalproses', [MohklruangController::class, 'mohklruangbatalproses'])->name('mohklruangbatalproses');
  Route::get('mohklruangbatalprosesok', [MohklruangController::class, 'mohklruangbatalprosesok'])->name('mohklruangbatalprosesok');
  //Kasir keluar
  Route::resource('/kasir_keluar', \App\Http\Controllers\Kasir_keluarController::class);
  Route::get('kasir_keluarajax', [Kasir_keluarController::class, 'kasir_keluarajax'])->name('kasir_keluarajax');
  Route::get('kasir_keluarupdate', [Kasir_keluarController::class, 'update'])->name('update');
  Route::resource('/kasir_keluard', \App\Http\Controllers\Kasir_keluardController::class);
  Route::get('kasir_keluardajax', [Kasir_keluardController::class, 'kasir_keluardajax'])->name('kasir_keluardajax');
  Route::get('kasir_keluartambahdetail', [Kasir_keluardController::class, 'kasir_keluartambahdetail'])->name('kasir_keluartambahdetail');
  Route::get('kasir_keluartotaldetail', [Kasir_keluardController::class, 'kasir_keluartotaldetail'])->name('kasir_keluartotaldetail');
  Route::get('kasir_keluarinputkasir_keluard', [Kasir_keluardController::class, 'kasir_keluarinputkasir_keluard'])->name('kasir_keluarinputkasir_keluard');
  Route::get('kasir_keluardstore', [Kasir_keluardController::class, 'store'])->name('kasir_keluardstore');
  Route::get('kasir_keluardupdate', [Kasir_keluardController::class, 'update'])->name('update');
  Route::post('kasir_keluarproses/{kasir_keluarproses}', [Kasir_keluarController::class, 'kasir_keluarproses'])->name('kasir_keluarproses');
  Route::post('kasir_keluarunproses', [Kasir_keluarController::class, 'kasir_keluarunproses'])->name('kasir_keluarunproses');
  Route::post('kasir_keluarcancel', [Kasir_keluarController::class, 'kasir_keluarcancel'])->name('kasir_keluarcancel');
  Route::post('kasir_keluarambil', [Kasir_keluarController::class, 'kasir_keluarambil'])->name('kasir_keluarambil');
  Route::get('kasir_keluarcetak', [Kasir_keluarController::class, 'kasir_keluarCetak'])->name('kasir_keluarcetak');
  Route::get('kasir_keluarbatalproses', [Kasir_keluarController::class, 'kasir_keluarbatalproses'])->name('kasir_keluarbatalproses');
  Route::get('kasir_keluarbatalprosesok', [Kasir_keluarController::class, 'kasir_keluarbatalprosesok'])->name('kasir_keluarbatalprosesok');
  //Proses
  // Route::get('closing_harian', [ReportController::class, 'closing_harian'])->name('closing_harian');
  // Route::post('closing_harian_proses', [ReportController::class, 'closing_harian_proses'])->name('closing_harian_proses');
  // Route::get('closing_hpp', [ReportController::class, 'closing_hpp'])->name('closing_hpp');
  // Route::post('closing_hpp_proses', [ReportController::class, 'closing_hpp_proses'])->name('closing_hpp_proses');
  // Route::get('closing_harian', [ReportController::class, 'closing_harian'])->name('closing_harian');
  // Route::post('closing_harian_proses', [ReportController::class, 'closing_harian_proses'])->name('closing_harian_proses');
  // Route::get('proses_stock', [ReportController::class, 'proses_stock'])->name('proses_stock');
  // Route::post('proses_stock_proses', [ReportController::class, 'proses_stock_proses'])->name('proses_stock_proses');
  // Route::get('backup', [ReportController::class, 'backup'])->name('backup');
  // Route::post('backup_proses', [ReportController::class, 'backup_proses'])->name('backup_proses');
  //Report-Report
  Route::get('rfaktur', [ReportController::class, 'rfaktur'])->name('rfaktur');
  Route::post('rfaktur_xls', [ReportController::class, 'rfaktur_xls'])->name('rfaktur_xls');
  Route::get('rfaktur_export', [ReportController::class, 'rfaktur_export'])->name('rfaktur_export');
  Route::get('rso', [ReportController::class, 'rso'])->name('rso');
  Route::post('rso_xls', [ReportController::class, 'rso_xls'])->name('rso_xls');
  Route::get('rso_export', [ReportController::class, 'rso_export'])->name('rso_export');
  Route::get('rjual', [ReportController::class, 'rjual'])->name('rjual');
  Route::post('rjual_xls', [ReportController::class, 'rjual_xls'])->name('rjual_xls');
  Route::get('rjual_export', [ReportController::class, 'rjual_export'])->name('rjual_export');
  Route::get('rrating', [ReportController::class, 'rrating'])->name('rrating');
  Route::post('rrating_xls', [ReportController::class, 'rrating_xls'])->name('rrating_xls');
  Route::get('rrating_export', [ReportController::class, 'rrating_export'])->name('rrating_export');
  Route::get('rpo', [ReportController::class, 'rpo'])->name('rpo');
  Route::post('rpo_xls', [ReportController::class, 'rpo_xls'])->name('rpo_xls');
  Route::get('rpo_export', [ReportController::class, 'rpo_export'])->name('rpo_export');
  Route::get('rbeli', [ReportController::class, 'rbeli'])->name('rbeli');
  Route::post('rbeli_xls', [ReportController::class, 'rbeli_xls'])->name('rbeli_xls');
  Route::get('rbeli_export', [ReportController::class, 'rbeli_export'])->name('rbeli_export');
  Route::get('rterima', [ReportController::class, 'rterima'])->name('rterima');
  Route::post('rterima_xls', [ReportController::class, 'rterima_xls'])->name('rterima_xls');
  Route::get('rterima_export', [ReportController::class, 'rterima_export'])->name('rterima_export');
  Route::get('rkeluar', [ReportController::class, 'rkeluar'])->name('rkeluar');
  Route::post('rkeluar_xls', [ReportController::class, 'rkeluar_xls'])->name('rkeluar_xls');
  Route::get('rkeluar_export', [ReportController::class, 'rkeluar_export'])->name('rkeluar_export');
  Route::get('rstock_opname', [ReportController::class, 'rstock_opname'])->name('rstock_opname');
  Route::post('rstock_opname_xls', [ReportController::class, 'rstock_opname_xls'])->name('rstock_opname_xls');
  Route::get('rstock_opname_export', [ReportController::class, 'rstock_opname_export'])->name('rstock_opname_export');
  Route::get('rstock', [ReportController::class, 'rstock'])->name('rstock');
  Route::post('rstock_xls', [ReportController::class, 'rstock_xls'])->name('rstock_xls');
  Route::get('rstock_export', [ReportController::class, 'rstock_export'])->name('rstock_export');
  Route::get('rhpp', [ReportController::class, 'rhpp'])->name('rhpp');
  Route::post('rhpp_xls', [ReportController::class, 'rhpp_xls'])->name('rhpp_xls');
  Route::get('rhpp_export', [ReportController::class, 'rhpp_export'])->name('rhpp_export');
  Route::get('rkasir_tunai', [ReportController::class, 'rkasir_tunai'])->name('rkasir_tunai');
  Route::post('rkasir_tunai_xls', [ReportController::class, 'rkasir_tunai_xls'])->name('rkasir_tunai_xls');
  Route::get('rkasir_tunai_export', [ReportController::class, 'rkasir_tunai_export'])->name('rkasir_tunai_export');
  Route::get('rkasir_tagihan', [ReportController::class, 'rkasir_tagihan'])->name('rkasir_tagihan');
  Route::post('rkasir_tagihan_xls', [ReportController::class, 'rkasir_tagihan_xls'])->name('rkasir_tagihan_xls');
  Route::get('rkasir_tagihan_export', [ReportController::class, 'rkasir_tagihan_export'])->name('rkasir_tagihan_export');
  Route::get('rpermohonan_keluar_uang', [ReportController::class, 'rpermohonan_keluar_uang'])->name('rpermohonan_keluar_uang');
  Route::post('rpermohonan_keluar_uang_xls', [ReportController::class, 'rpermohonan_keluar_uang_xls'])->name('rpermohonan_keluar_uang_xls');
  Route::get('rpermohonan_keluar_uang_export', [ReportController::class, 'rpermohonan_keluar_uang_export'])->name('rpermohonan_keluar_uang_export');
  Route::get('rkasir_keluar', [ReportController::class, 'rkasir_keluar'])->name('rkasir_keluar');
  Route::post('rkasir_keluar_xls', [ReportController::class, 'rkasir_keluar_xls'])->name('rkasir_keluar_xls');
  Route::get('rkasir_keluar_export', [ReportController::class, 'rkasir_keluar_export'])->name('rkasir_keluar_export');
  Route::get('rpiutang', [ReportController::class, 'rpiutang'])->name('rpiutang');
  Route::post('rpiutang_xls', [ReportController::class, 'rpiutang_xls'])->name('rpiutang_xls');
  Route::get('rpiutang_export', [ReportController::class, 'rpiutang_export'])->name('rpiutang_export');
  Route::get('rhutang', [ReportController::class, 'rhutang'])->name('rhutang');
  Route::post('rhutang_xls', [ReportController::class, 'rhutang_xls'])->name('rhutang_xls');
  Route::get('rhutang_export', [ReportController::class, 'rhutang_export'])->name('rhutang_export');
  //Proses Menu
  Route::get('closing_harian', [ProsesController::class, 'closing_harian'])->name('closing_harian');
  Route::get('closing_harian_proses', [ProsesController::class, 'closing_harian_proses'])->name('closing_harian_proses');
  Route::get('closing_hpp', [ProsesController::class, 'closing_hpp'])->name('closing_hpp');
  Route::get('closing_hpp_proses', [ProsesController::class, 'closing_hpp_proses'])->name('closing_hpp_proses');
  Route::get('closing_hpp_unproses', [ProsesController::class, 'closing_hpp_unproses'])->name('closing_hpp_unproses');
  Route::get('proses_stock', [ProsesController::class, 'proses_stock'])->name('proses_stock');
  Route::get('proses_stock_proses', [ProsesController::class, 'proses_stock_proses'])->name('proses_stock_proses');
  Route::get('backup', [ProsesController::class, 'backup'])->name('backup');
  Route::get('backup_proses', [ProsesController::class, 'backup_proses'])->name('backup_proses');
});

Route::get('/link', function () {
  Artisan::call('storage:link');
  echo 'ok';
});
Route::get('/linkstorage', function () {
  $targetFolder = base_path() . '/storage/app/public';
  $linkFolder = $_SERVER['DOCUMENT_ROOT'] . '/storage';
  symlink($targetFolder, $linkFolder);
});
Route::get('generate', function () {
  \Illuminate\Support\Facades\Artisan::call('storage:link');
  echo 'ok';
});

Route::get('/', [LoginController::class, 'index'])->name('login');
Route::post('actionlogin', [LoginController::class, 'actionlogin'])->name('actionlogin');

//REGISTER
Route::get('register', [RegisterController::class, 'register'])->name('register');
Route::post('register/action', [RegisterController::class, 'actionregister'])->name('actionregister');
